[package]
name = "atc-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto-traffic-control = "0.3.2"
tonic = "*"
tokio = { version = "1", features = ["full"] }